# Training Configuration
# ===================

#------------------------------------------------------------------------------
# Model Architecture
#------------------------------------------------------------------------------
# These settings define the core neural network architecture including
# layer sizes, activation functions, and other structural parameters.

model:
  hidden_layers: [128, 64]
  activation: "relu"
  dropout_rate: 0.2
  input_shape: [28, 28]
  output_classes: 10

#------------------------------------------------------------------------------
# Training Parameters
#------------------------------------------------------------------------------
# Core parameters that control the training process including batch size,
# number of epochs, learning rate, and data splitting ratios.

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  validation_split: 0.2
  early_stopping_patience: 5
  reduce_lr_patience: 3
  reduce_lr_factor: 0.2
  shuffle_buffer_size: 10000

#------------------------------------------------------------------------------
# Data Augmentation
#------------------------------------------------------------------------------
# Settings for real-time data augmentation during training to improve
# model generalization and prevent overfitting.

augmentation:
  enabled: true
  rotation_range: 10
  width_shift: 0.1
  height_shift: 0.1
  zoom_range: 0.1
  horizontal_flip: false 