# Environment Configuration
# =======================


#------------------------------------------------------------------------------
# Data Management
#------------------------------------------------------------------------------
# Settings for data storage, caching, and preprocessing. These control
# where data is stored and how it's processed before being used for
# training or inference.

data:
  base_dir: "None"
  raw_dir: "raw"
  processed_dir: "processed"
  cache_dir: ".cache"
  temp_dir: "/tmp/ml-tensorflow"
  max_cache_size: 10  # GB
  compression_format: "gzip"

#------------------------------------------------------------------------------
# Logging and Monitoring
#------------------------------------------------------------------------------
# Configuration for logging, monitoring, and alerting systems. These
# settings control how the application tracks and reports its operation
# and performance.

monitoring:
  log_level: "INFO"
  enable_file_logging: true
  log_dir: "logs"
  monitoring_interval: 60  # seconds
  alert_threshold: 0.85
  enable_mlflow: true
  enable_wandb: false
  metrics_tracking: true 