# Environment Configuration
# =======================


#------------------------------------------------------------------------------
# Data Management
#------------------------------------------------------------------------------
# Settings for data storage, caching, and preprocessing. These control
# where data is stored and how it's processed before being used for
# training or inference.

data:
  base_dir: "data" # Base directory for data storage
  raw_dir: "data/raw" # Directory for raw data
  processed_dir: "data/processed" # Directory for processed data
  cache_dir: ".cache" # Directory for cached data
  temp_dir: "data/tmp/ml-tensorflow" # Temporary directory
  max_cache_size: 10  # GB (0 for unlimited)
  compression_format: "gzip" # Compression format for cached data

#------------------------------------------------------------------------------
# Logging and Monitoring
#------------------------------------------------------------------------------
# Configuration for logging, monitoring, and alerting systems. These
# settings control how the application tracks and reports its operation
# and performance.

monitoring:
  logger_name: "ml-tensorflow" # Name of the logger
  log_level: "info" # debug, info, success, warning, error, critical
  enable_file_logging: true # Save logs to a file
  store_verbose_logs: true # Store verbose logs in memory
  log_dir: "logs" # Directory to save logs
  monitoring_interval: 60  # seconds
  alert_threshold: 0.85 # Threshold for alerts
  enable_mlflow: true # Enable MLflow for experiment tracking
  enable_wandb: false # Enable Weights & Biases for experiment tracking
  metrics_tracking: true # Enable tracking of metrics

#------------------------------------------------------------------------------
# TensorBoard Visualization
#------------------------------------------------------------------------------
# Configuration for TensorBoard, the visualization tool for TensorFlow.
# These settings control how TensorBoard is configured and used.

tensorboard:
  enable: true # Enable TensorBoard
  log_dir: "logs/tensorboard" # Directory to save TensorBoard logs
  port: 6006 # Port for TensorBoard server
  update_interval: 60  # seconds (0 for no updates)
