[tool.pyright]
include = ["src", "ci", "tests"]
exclude = [
    "**/__pycache__",
    "**/.venv",
    "**/venv",
    "**/env",
    "**/.env",
]
venv = ".venv"
venvPath = "."
typeCheckingMode = "basic"
useLibraryCodeForTypes = true
reportMissingImports = true
reportMissingTypeStubs = false 